info:
  title: NotionAiOS
  description: A plugin for interacting with Notion
  version: 'v1'
servers:
  - url: http://localhost:4000/notion_manager
paths:
  /:
    post: 
      operationId: getBlocks
      summary: Get all the blocks on a page
      requestBody: 
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetBlocksRequest' 
      responses: 
        "200":
          description: OK
          content:
            application/json: 
              schema: 
                $ref: '#/components/schemas/GetBlocksResponse' 
  /codeBlock:
    post:
      operationId: codeBlock
      summary: Update the contents of an existing code block.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCodeBlockRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateCodeBlockResponse'
components:
  schemas:
    GetBlocksRequest: 
      type: object
      required:
        - pageId
      properties: 
        pageId:
          type: string
          description: the ID of the page
    GetBlocksResponse: 
      type: object
      properties: 
        messageResponse:
          type: string
          description: the response message  
    UpdateCodeBlockRequest:
      type: object
      required:
        - command
        - blockId
        - startLine
        - endLine
      properties:
        command:  
          type: string
          description: Should be either "DELETE LINES" or "REPLACE LINES"
        blockId:
          type: string
          description: The ID of the code block to be updated.
        code:
          type: string
          description: The new code to replace the current lines - only use if you are using the "REPLACE LINES" command
        startLine:
          type: number
          description: The first line number
        endLine:
          type: number
          description: The end line number - always use, if you want to act on one line your start and end line should be the same. (inclusive)
    UpdateCodeBlockResponse:
      type: object
      properties: 
        messageResponse:
          type: string
          description: The results of request
