info:
  title: NotionAiOS
  description: A plugin for interacting with Notion
  version: 'v1'
servers:
  - url: https://v3rv-notionaios.web.app/api
paths:
  /pageActions:
    post:
      operationId: pageActions
      summary: Use to update the code on a page
      requestBody: 
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PageActionsRequest'
  /project:
    post: 
      operationId: createProject
      summary: Create a new project in the users workspace
      requestBody: 
        required: true
        content: 
          application/json:
            schema: 
              $ref: '#/components/schemas/CreateProjectRequest'
  /pages:
    post:
      operationId: createPage
      summary: Create a new page
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePageRequest'
  /tags: 
    post: 
      operationId: updateTags
      summary: Update a projects tags
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTagsRequest'

  /downloadLink: 
    post:
      operationId: downloadProject
      summary: Get a download link for a zip of the current project
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetDownloadLinkRequest'

components:
  schemas:
    UpdateTagsRequest: 
      type: object
      required: 
        - userId
        - projectName
        - tags
      properties: 
        userId: 
          type: string
          description: The userId 
        projectName:
          type: string
          description: The name of the project
        tags:
          type: array
          items:
            type: string
          description: An array of the tags to add to the project

    CreateProjectRequest: 
      type: object
      required: 
        - userId
        - projectName
      properties: 
        userId: 
          type: string
          description: The userId 
        projectName:
          type: string
          description: The name of the project you are trying to create

    GetDownloadLinkRequest: 
      type: object
      required: 
        - userId
      properties: 
        userId: 
          type: string
          description: The userId 
        projectName:
          type: string
          description: The name of the project you wish to download

    PageActionsRequest: 
      type: object
      required:
        - userId
        - projectName
        - command
      properties: 
        userId: 
          type: string
          description: The userId 
        projectName:
          type: string
          description: The name of the project the page belongs to
        command: 
          type: string
          description: Should be either "REPLACE CODE" or "ADD CODE"
        pageName:
          type: string
          description: the name of the page, including the extension (.ts, js, .java, etc)
        code:
          type: string
          description: the code you wish to add to the page
        startLine: 
          type: string
          description: the startline of the code you want to replace ( for replacing code only ), inclusive
        endLine: 
          type: string
          description: the endLine of the code you want to replace ( for replacing code only ), inclusive

    CreatePageRequest:
      type: object
      required: 
        - userId
        - projectName
        - parentName
        - pageName
        - type
      properties: 
        userId: 
          type: string
          description: The userID of the user making the request
        projectName: 
          type: string
          description: The project name
        parentName: 
          type: string
          description: The name of the new page's parent folder
        pageName: 
          type: string
          description: The name of the new page
        type: 
          type: string
          description: The filetype of the new page (ex. folder, rust, javascript... etc)
